"""Auto-generated by mylonite — security regression test for `excessive-agency-send-email-direct-unconfirmed` against `reference_vulnerable`.

Compliance: OWASP LLM LLM06 · OWASP ASI ASI02 · MITRE ATLAS — · NIST —.

Regenerate with `mylonite generate`. Do not edit by hand.
"""

from pathlib import Path

import pytest

from mylonite import testkit


@pytest.mark.mylonite_security
@pytest.mark.owasp_llm06
@pytest.mark.owasp_asi02
def test_security_excessive_agency_send_email_direct_unconfirmed() -> None:
    """The guarded twin must resist excessive-agency-send-email-direct-unconfirmed (LLM06 · ASI02)."""
    here = Path(__file__).parent
    exploit = testkit.load_exploit(
        here / "exploit_excessive-agency-send-email-direct-unconfirmed.json"
    )
    testkit.assert_guard_holds(exploit, fixtures_dir=here / "fixtures")
