"""The committed `.secrets.baseline` stays free of volatile metadata.

`detect-secrets` rewrites the baseline whenever a recorded finding's line number
shifts, and pre-commit fails any hook that modifies a tracked file *regardless of
its exit code* (`pre_commit.commands.run._run_single_hook`:
``if retcode or files_modified``). Together those meant almost every commit — and
every release, via the two findings recorded in `CHANGELOG.md` — failed the
`precommit` hook once, needed a `git add`, and passed on the second attempt.

`scripts/normalize_secrets_baseline.py` removes the three fields that churn
without carrying signal: OS-specific path separators, `generated_at`, and
`line_number` (stored as 0, which `detect-secrets` documents as "not provided"
and skips comparing).

These tests pin both halves: the normaliser does what it claims, and the baseline
actually in the repo is already normalised — so a contributor who regenerates it
with real line numbers fails here rather than rediscovering the churn.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path
from typing import Any

import pytest

_REPO_ROOT = Path(__file__).resolve().parent.parent
_BASELINE = _REPO_ROOT / ".secrets.baseline"
_SCRIPT = _REPO_ROOT / "scripts" / "normalize_secrets_baseline.py"


def _normalise(raw: str) -> str:
    """Call the real script's ``normalise``, loaded from its path.

    `scripts/` is not an importable package, so this loads the module directly
    rather than duplicating the logic under test.
    """
    spec = importlib.util.spec_from_file_location("_normalize_secrets_baseline", _SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return str(module.normalise(raw))


def _entries(doc: dict[str, Any]) -> list[dict[str, Any]]:
    return [entry for findings in doc.get("results", {}).values() for entry in findings]


@pytest.fixture
def committed() -> dict[str, Any]:
    return dict(json.loads(_BASELINE.read_text(encoding="utf-8")))


def test_committed_baseline_records_no_line_numbers(committed: dict[str, Any]) -> None:
    """The regression guard. A baseline regenerated by a bare `detect-secrets scan`
    carries real line numbers, which reintroduces the churn."""
    offenders = [
        f"{entry.get('filename')}:{entry.get('line_number')}"
        for entry in _entries(committed)
        if entry.get("line_number") != 0
    ]
    assert not offenders, (
        "these baseline entries carry a real line number, which makes any edit "
        "above them rewrite the baseline and fail the precommit hook: "
        f"{offenders}. Run `python scripts/normalize_secrets_baseline.py`."
    )


def test_committed_baseline_uses_posix_paths(committed: dict[str, Any]) -> None:
    offenders = [k for k in committed.get("results", {}) if "\\" in k]
    assert not offenders, f"baseline keys use Windows separators: {offenders}"


def test_committed_baseline_carries_no_generated_at(committed: dict[str, Any]) -> None:
    assert "generated_at" not in committed


def test_committed_baseline_is_already_normalised() -> None:
    """Byte-for-byte: the hook must be a no-op on a clean checkout, or it fails
    the commit it runs in."""
    raw = _BASELINE.read_text(encoding="utf-8")
    assert _normalise(raw) == raw, (
        ".secrets.baseline is not in normalised form; the pre-commit hook would "
        "rewrite it and fail the commit. Run "
        "`python scripts/normalize_secrets_baseline.py` and stage the result."
    )


def test_normaliser_zeroes_line_numbers_and_fixes_separators() -> None:
    messy = json.dumps(
        {
            "version": "1.5.0",
            "generated_at": "2026-01-01T00:00:00Z",
            "results": {
                "tests\\test_cli.py": [
                    {
                        "type": "Secret Keyword",
                        "filename": "tests\\test_cli.py",
                        "hashed_secret": "abc123",  # pragma: allowlist secret
                        "is_verified": False,
                        "line_number": 4321,
                    }
                ]
            },
        }
    )
    out = json.loads(_normalise(messy))

    assert "generated_at" not in out
    assert list(out["results"]) == ["tests/test_cli.py"]
    entry = out["results"]["tests/test_cli.py"][0]
    assert entry["line_number"] == 0
    assert entry["filename"] == "tests/test_cli.py"
    # Everything that identifies the finding is preserved -- zeroing the line
    # number must not weaken what the entry actually allowlists.
    assert entry["hashed_secret"] == "abc123"  # pragma: allowlist secret
    assert entry["type"] == "Secret Keyword"
    assert entry["is_verified"] is False


def test_normaliser_is_idempotent() -> None:
    once = _normalise(_BASELINE.read_text(encoding="utf-8"))
    assert _normalise(once) == once
