"""Auto-generated by mylonite — security regression test for `indirect-injection-note-body-tool-chain` against `reference_vulnerable`.

Compliance: OWASP LLM LLM01 · OWASP ASI ASI01 · MITRE ATLAS AML.T0051 · NIST —.

Regenerate with `mylonite generate`. Do not edit by hand.
"""

from pathlib import Path

import pytest

from mylonite import testkit


@pytest.mark.mylonite_security
@pytest.mark.owasp_llm01
@pytest.mark.owasp_asi01
@pytest.mark.atlas_aml_t0051
def test_security_indirect_injection_note_body_tool_chain() -> None:
    """The guarded twin must resist indirect-injection-note-body-tool-chain (LLM01 · ASI01 · AML.T0051)."""
    here = Path(__file__).parent
    exploit = testkit.load_exploit(here / "exploit_indirect-injection-note-body-tool-chain.json")
    testkit.assert_guard_holds(exploit, fixtures_dir=here / "fixtures")
