"""Reference pytest generator — emits a real testkit-based regression test.

Given a confirmed :class:`ExploitRecord`, :meth:`ReferencePytestGenerator.emit`
renders a deterministic, self-contained pytest file. The emitted test imports
the public :mod:`mylonite.testkit` API and, at runtime, replays the recorded
attack against the GUARDED reference twin via
:func:`mylonite.testkit.assert_guard_holds` — the offline regression gate.

Two properties are load-bearing:

* **Deterministic.** No LLM call, no timestamp, no randomness; the taxonomy IDs
  are sorted before rendering. The same exploit always emits byte-identical
  source, so the output is snapshot-testable.
* **Collects without data files.** ``load_exploit`` / ``assert_guard_holds`` live
  INSIDE the test function body (not at module level), so the file *collects*
  cleanly even before the ``exploit_<pattern_id>.json`` artefact / fixtures are
  present. Only running the test needs them.

Every emitted marker (``mylonite_security`` plus the bounded OWASP
``owasp_llm0N`` / ``owasp_asi0N`` set) is registered by the bundled pytest
plugin (``mylonite.testkit._pytest_plugin``, auto-loaded via the ``pytest11``
entry point), so the file is warning-free even under ``filterwarnings = error``.
"""

from __future__ import annotations

from typing import ClassVar, Literal

from mylonite.contracts import ExploitRecord, GeneratedTest, TestGeneratorBase
from mylonite.contracts.test_generator import CONTRACT_VERSION

_TEMPLATE = '''"""Auto-generated by mylonite — security regression test for `{pattern_id}` \
against `{target_id}`.

Compliance: OWASP LLM {owasp_llm} · OWASP ASI {owasp_asi} · \
MITRE ATLAS {mitre_atlas} · NIST {nist}.

Regenerate with `mylonite generate`. Do not edit by hand.
"""

from pathlib import Path

import pytest

from mylonite import testkit

{decorators}
def test_security_{slug}() -> None:
    """The guarded twin must resist {pattern_id} ({compliance_inline})."""
    here = Path(__file__).parent
    exploit = testkit.load_exploit(here / "exploit_{pattern_id}.json")
    testkit.assert_guard_holds(exploit, fixtures_dir=here / "fixtures")
'''


def _slugify(pattern_id: str) -> str:
    """Turn a ``pattern_id`` into a valid Python identifier suffix.

    Any character that is not a valid identifier char (``-``, ``.``, etc.) is
    collapsed to ``_``. Deterministic and stable.
    """
    return "".join(ch if ch.isalnum() else "_" for ch in pattern_id)


def _fmt_ids(ids: list[str]) -> str:
    """Render a sorted, comma-joined ID list for the docstring (``—`` if empty)."""
    return ", ".join(sorted(ids)) if ids else "—"


class ReferencePytestGenerator(TestGeneratorBase):
    """Emits a deterministic, testkit-based pytest regression test."""

    contract_version: ClassVar[str] = CONTRACT_VERSION

    def framework(self) -> Literal["pytest", "jest"]:
        return "pytest"

    def emit(self, exploit: ExploitRecord) -> GeneratedTest:
        slug = _slugify(exploit.pattern_id)
        compliance = exploit.compliance

        # Bounded OWASP markers only — registered by the pytest11 plugin. ATLAS /
        # NIST IDs are unbounded, so they ride in the docstring (not as markers).
        markers: list[str] = ["@pytest.mark.mylonite_security"]
        for llm_id in sorted(compliance.owasp_llm):
            markers.append(f"@pytest.mark.owasp_{llm_id.lower()}")
        for asi_id in sorted(compliance.owasp_asi):
            markers.append(f"@pytest.mark.owasp_{asi_id.lower()}")
        decorators = "\n".join(markers)

        # Inline compliance summary for the test docstring (sorted, stable).
        inline_parts: list[str] = []
        for llm_id in sorted(compliance.owasp_llm):
            inline_parts.append(llm_id)
        for asi_id in sorted(compliance.owasp_asi):
            inline_parts.append(asi_id)
        for atlas_id in sorted(compliance.mitre_atlas):
            inline_parts.append(atlas_id)
        for nist_id in sorted(compliance.nist_ai_rmf):
            inline_parts.append(nist_id)
        compliance_inline = " · ".join(inline_parts) if inline_parts else "no tags"

        source = _TEMPLATE.format(
            pattern_id=exploit.pattern_id,
            target_id=exploit.target_id,
            slug=slug,
            decorators=decorators,
            compliance_inline=compliance_inline,
            owasp_llm=_fmt_ids(compliance.owasp_llm),
            owasp_asi=_fmt_ids(compliance.owasp_asi),
            mitre_atlas=_fmt_ids(compliance.mitre_atlas),
            nist=_fmt_ids(compliance.nist_ai_rmf),
        )

        return GeneratedTest(
            framework="pytest",
            filename=f"test_security_{slug}.py",
            source=source,
            exploit=exploit,
        )
