"""Reference pytest generator — emits a real testkit-based regression test.

Given a confirmed :class:`ExploitRecord`, :meth:`ReferencePytestGenerator.emit`
renders a deterministic, self-contained pytest file. The emitted test imports
the public :mod:`mylonite.testkit` API and, at runtime, replays the recorded
attack against the GUARDED reference twin via
:func:`mylonite.testkit.assert_guard_holds` — the offline regression gate.

Two properties are load-bearing:

* **Deterministic.** No LLM call, no timestamp, no randomness; the taxonomy IDs
  are sorted before rendering. The same exploit always emits byte-identical
  source, so the output is snapshot-testable.
* **Collects without data files.** ``load_exploit`` / ``assert_guard_holds`` live
  INSIDE the test function body (not at module level), so the file *collects*
  cleanly even before the ``exploit_<pattern_id>.json`` artefact / fixtures are
  present. Only running the test needs them.

Every emitted marker (``mylonite_security``, the bounded OWASP
``owasp_llm0N`` / ``owasp_asi0N`` set, plus the bundled-taxonomy ATLAS
``atlas_*`` and NIST ``nist_*`` sets) is registered by the bundled pytest
plugin (``mylonite.testkit._pytest_plugin``, auto-loaded via the ``pytest11``
entry point), so the file is warning-free even under ``filterwarnings = error``.
"""

from __future__ import annotations

import re
from typing import ClassVar, Literal

from mylonite.contracts import ExploitRecord, GeneratedTest, TestGeneratorBase
from mylonite.contracts.exec_context import ExecContext
from mylonite.contracts.test_generator import CONTRACT_VERSION
from mylonite.testkit._pytest_plugin import (
    MYLONITE_SECURITY_MARKER,
    REGISTERED_ATLAS_MARKERS,
    REGISTERED_NIST_MARKERS,
    REGISTERED_OWASP_MARKERS,
    _marker_name,
)

_TEMPLATE = '''"""Auto-generated by mylonite — security regression test for `{pattern_id}` \
against `{target_id}`.

Compliance: OWASP LLM {owasp_llm} · OWASP ASI {owasp_asi} · \
MITRE ATLAS {mitre_atlas} · NIST {nist}.

Regenerate with `mylonite generate`. Do not edit by hand.
"""

from pathlib import Path

import pytest

from mylonite import testkit

{decorators}
def test_security_{slug}() -> None:
    """The guarded twin must resist {pattern_id} ({compliance_inline})."""
    here = Path(__file__).parent
    exploit = testkit.load_exploit(here / {exploit_filename})
    testkit.assert_guard_holds(exploit, fixtures_dir=here / "fixtures")
'''


_TEMPLATE_CUSTOM = '''"""Auto-generated by mylonite — security regression test for `{pattern_id}` \
against `{target_id}`.

Compliance: OWASP LLM {owasp_llm} · OWASP ASI {owasp_asi} · \
MITRE ATLAS {mitre_atlas} · NIST {nist}.

This test re-drives the REAL target ({target_id}) and asserts it still RESISTS
the attack — it FAILS if your app regresses (the attack lands / its effect probe
confirms damage). It launches the target's MCP server and calls the provider, so
it is gated behind MYLONITE_LIVE_TARGET=1. It needs the target's `target.yaml`
co-located next to this test: pass `mylonite generate --target-file <your-target>.yaml`
(it writes target.yaml here for you), or copy your scan's target YAML in as target.yaml.

Regenerate with `mylonite generate`. Do not edit by hand.
"""

import os
from pathlib import Path

import pytest

from mylonite import testkit

{decorators}
@pytest.mark.skipif(
    os.environ.get("MYLONITE_LIVE_TARGET") != "1",
    reason="re-drives the real target live; set MYLONITE_LIVE_TARGET=1 to run",
)
def test_security_{slug}() -> None:
    """{target_id} must remain resistant to {pattern_id} ({compliance_inline})."""
    here = Path(__file__).parent
    exploit = testkit.load_exploit(here / {exploit_filename})
    testkit.assert_target_resists(exploit, target_file=here / "target.yaml"{model_kwarg}{provider_kwarg})
'''


_TEMPLATE_CONTROL = '''"""Auto-generated by mylonite — control-efficacy regression test for `{pattern_id}` \
against `{target_id}`.

Compliance: OWASP LLM {owasp_llm} · OWASP ASI {owasp_asi} · \
MITRE ATLAS {mitre_atlas} · NIST {nist}.

Control `{control_display}` is verified LOAD-BEARING for this target's model: the attack
lands without it and is RESISTED with it (applied at the adapter boundary). This
test FAILS if the control stops carrying the security — either the boundary
control no longer blocks the attack, or (once you implement the control
server-side) your implementation regresses.

Boundary-validated control (proxy): mylonite enforces the control at the adapter
boundary, not in your server. Implement it server-side for a production fix (see
the mitigation in the PR), then re-point this test at your real implementation.

It launches the target's MCP server and calls the provider, so it is gated
behind MYLONITE_LIVE_TARGET=1. It needs the target's `target.yaml` co-located
next to this test.

Regenerate with `mylonite generate`. Do not edit by hand.
"""

import os
from pathlib import Path

import pytest

from mylonite import testkit

{decorators}
@pytest.mark.skipif(
    os.environ.get("MYLONITE_LIVE_TARGET") != "1",
    reason="re-drives the real target live; set MYLONITE_LIVE_TARGET=1 to run",
)
def test_security_{slug}() -> None:
    """Control {control_display} must keep blocking {pattern_id} on {target_id} \
({compliance_inline})."""
    here = Path(__file__).parent
    exploit = testkit.load_exploit(here / {exploit_filename})
    testkit.assert_control_holds(exploit, target_file=here / "target.yaml", control={control_literal}{model_kwarg}{provider_kwarg})
'''


#: A pattern_id is a stable identifier that becomes BOTH a filename and a Python
#: identifier suffix. It can originate in a probed target's tool name (via
#: seed_synth), so it is attacker-influenceable and is validated, not sanitised —
#: silently rewriting it would desynchronise the emitted `load_exploit` filename
#: from the artefact `_emit_generated_test` writes.
#:
#: The trailing character is constrained the same as the leading one (must be
#: alphanumeric, not `.`/`_`/`-`) because `_emit_generated_test` in cli.py
#: writes the co-located exploit JSON via `safe_slug(pattern_id)`, and
#: `safe_slug` strips trailing `.`/`_`/`-`. A pattern_id ending in one of
#: those (e.g. "foo-") would pass this regex unstripped, so the emitted
#: `load_exploit(here / 'exploit_foo-.json')` call would look for a file that
#: doesn't exist -- `safe_slug` would have written `exploit_foo.json`. No
#: pattern_id in this codebase currently ends that way, but the mismatch is
#: exactly the desync class this validation exists to prevent, so it is
#: closed here too rather than left dormant.
_SAFE_PATTERN_ID = re.compile(r"^[A-Za-z0-9]([A-Za-z0-9._-]{0,126}[A-Za-z0-9])?$")


class UnsafeExploitRecord(ValueError):
    """Raised when an ExploitRecord carries a field unsafe to render into source."""


def _py_literal(value: object) -> str:
    """Render ``value`` as a Python source literal.

    ``repr()`` of a ``str`` is always a valid, fully-escaped Python literal, so
    a value containing quotes, backslashes, or newlines cannot terminate the
    literal it sits in. Used for EVERY attacker-influenceable value the
    generator embeds (DCR-0001, DCR-0002).
    """
    return repr("" if value is None else str(value))


def _slugify(value: str) -> str:
    """Turn ``value`` into a valid Python identifier suffix.

    ``str.isalnum()`` is true for non-ASCII alphanumerics (e.g. ``²``, ``ⅷ``)
    that are not all valid in every identifier position, so it was never the
    right proxy (DCR-0028). Restrict to ASCII alnum and prefix a digit-leading
    slug so the emitted ``def test_security_<slug>`` always parses.

    Three callers, all attacker-influenceable strings that need a display- or
    identifier-safe form rather than rejection:

    * A validated ``pattern_id`` (see :data:`_SAFE_PATTERN_ID`) -> the test
      function's name suffix.
    * An unvalidated ``synthetic_control`` -> the DOCSTRING-safe preview.
      Unlike ``pattern_id``, ``control`` is rendered as a Python literal for
      the CODE site instead (see :func:`_py_literal`), so a hostile value can
      still contain three consecutive double-quote characters. Embedding
      those — even ``repr()``-quoted — bare inside the emitted module's
      triple-double-quoted docstring would terminate that docstring early and
      turn the remainder of the file into executable code, an injection
      distinct from (and not fixed by) quoting it as an argument literal.
      Slugifying it for display removes that sequence too, and is a no-op for
      realistic control names (e.g. ``"W2"``).
    * An unvalidated ``target_id`` (DCR-0006) -> the same DOCSTRING-safe
      preview, for the same reason. ``target_id`` (``mcp:<family>:<scope>``)
      has no CODE site at all in this file — it is interpolated ONLY into
      docstrings (module docstring in every template, plus the function
      docstring of ``_TEMPLATE_CUSTOM`` / ``_TEMPLATE_CONTROL``) — so
      ``_py_literal`` would not even help here: a ``repr()``-quoted value is
      safe as an argument literal, but the same text bare-embedded inside a
      *different* (docstring) string can still carry a live triple-double-quote
      sequence. ``TargetFile.family`` is a bare ``str`` with only a 3-reserved-name
      validator, so this is genuinely attacker-influenceable, not just
      theoretically so.
    """
    slug = "".join(ch if (ch.isascii() and ch.isalnum()) else "_" for ch in value)
    return f"_{slug}" if slug[:1].isdigit() else slug


def _fmt_ids(ids: list[str]) -> str:
    """Render a sorted, comma-joined ID list for the docstring (``—`` if empty)."""
    return ", ".join(sorted(ids)) if ids else "—"


class ReferencePytestGenerator(TestGeneratorBase):
    """Emits a deterministic, testkit-based pytest regression test."""

    contract_version: ClassVar[str] = CONTRACT_VERSION

    def framework(self) -> Literal["pytest", "jest"]:
        return "pytest"

    def emit(self, exploit: ExploitRecord, context: ExecContext | None = None) -> GeneratedTest:
        if not _SAFE_PATTERN_ID.fullmatch(exploit.pattern_id):
            msg = (
                f"pattern_id {exploit.pattern_id!r} is not safe to embed in generated "
                "source or an artefact path. Expected "
                f"{_SAFE_PATTERN_ID.pattern}. A pattern_id derived from a probed "
                "target's tool name must be slugified at synthesis time."
            )
            raise UnsafeExploitRecord(msg)

        slug = _slugify(exploit.pattern_id)
        compliance = exploit.compliance

        # Bounded OWASP markers only — and ONLY those the pytest11 plugin actually
        # registers (``REGISTERED_OWASP_MARKERS``). An out-of-range OWASP ID (e.g.
        # a future ``LLM11``) would otherwise emit an unregistered marker, which
        # under ``filterwarnings=error`` turns a consumer's committed test into a
        # hard collection error. Unregistered IDs fall back to the docstring, like
        # ATLAS / NIST.
        markers: list[str] = [f"@pytest.mark.{MYLONITE_SECURITY_MARKER}"]
        for tag in sorted(compliance.owasp_llm) + sorted(compliance.owasp_asi):
            marker_name = f"owasp_{tag.lower()}"
            if marker_name in REGISTERED_OWASP_MARKERS:
                markers.append(f"@pytest.mark.{marker_name}")
        # ATLAS / NIST markers, same registered-set guard: emit only names the
        # pytest11 plugin actually registers (bundled-taxonomy IDs); out-of-
        # taxonomy IDs fall back to the docstring. Shared ``_marker_name`` keeps
        # the emitted names byte-identical to the registered set.
        for atlas_id in sorted(compliance.mitre_atlas):
            marker_name = _marker_name("atlas", atlas_id)
            if marker_name in REGISTERED_ATLAS_MARKERS:
                markers.append(f"@pytest.mark.{marker_name}")
        for nist_id in sorted(compliance.nist_ai_rmf):
            marker_name = _marker_name("nist", nist_id)
            if marker_name in REGISTERED_NIST_MARKERS:
                markers.append(f"@pytest.mark.{marker_name}")
        decorators = "\n".join(markers)

        # Inline compliance summary for the test docstring (sorted, stable).
        inline_parts: list[str] = []
        for llm_id in sorted(compliance.owasp_llm):
            inline_parts.append(llm_id)
        for asi_id in sorted(compliance.owasp_asi):
            inline_parts.append(asi_id)
        for atlas_id in sorted(compliance.mitre_atlas):
            inline_parts.append(atlas_id)
        for nist_id in sorted(compliance.nist_ai_rmf):
            inline_parts.append(nist_id)
        compliance_inline = " · ".join(inline_parts) if inline_parts else "no tags"

        # A control-efficacy finding (synthetic_control metadata) replays via
        # assert_control_holds; otherwise reference targets replay against the bundled
        # twin (byte-for-byte unchanged) and a CUSTOM target re-drives the REAL app via
        # assert_target_resists.
        #
        # Branch on the VALUE, not key presence: a present-but-empty
        # synthetic_control previously selected the control template and
        # emitted `control=""` (DCR-0022).
        control = exploit.payload.metadata.get("synthetic_control") or ""
        if control:
            template = _TEMPLATE_CONTROL
        elif exploit.target_id.startswith("reference:"):
            template = _TEMPLATE
        else:
            template = _TEMPLATE_CUSTOM

        # DCR-0006: target_id is interpolated ONLY into docstrings below (never
        # a code site), so it gets the same treatment as control_display just
        # above — slugified for display. A bare `{target_id}` here let a
        # hostile value (TargetFile.family has no charset validation) embed a
        # `"""` that terminates the emitted module's own docstring early and
        # turns the remainder of the file into live top-level code.
        target_id_display = _slugify(exploit.target_id)

        # T12 (promoted to a real parameter in 0.7.10, CONTRACT_VERSION 0.2.0):
        # render the exec context as explicit model=/provider= literals in the
        # CUSTOM/CONTROL templates -- so the emitted CI gate re-drives the SAME
        # model that discovered/validated this finding, not testkit's own
        # hardcoded fallback default. Only the CUSTOM/CONTROL templates
        # reference these placeholders; harmless no-ops for the reference-twin
        # template (assert_guard_holds takes no model/provider kwargs at all).
        #
        # Prefer the explicit `context` parameter (0.7.10+ callers). Fall back
        # to re-deriving it from Payload.metadata (the T12 shim) only when no
        # context was passed -- either a caller that hasn't updated to the new
        # signature yet, or a pre-T12 exploit that carries no exec context at
        # all, in which case from_metadata() also returns None and no kwargs
        # are rendered -- testkit resolves it at RUN time instead (explicit
        # kwarg -> exec-context metadata -> sibling scan_report.json back-fill
        # -> loud failure).
        exec_ctx = (
            context if context is not None else ExecContext.from_metadata(exploit.payload.metadata)
        )
        model_kwarg = f", model={_py_literal(exec_ctx.model)}" if exec_ctx is not None else ""
        provider_kwarg = (
            f", provider={_py_literal(exec_ctx.provider)}" if exec_ctx is not None else ""
        )

        source = template.format(
            pattern_id=exploit.pattern_id,  # validated above; docstring use only
            # Docstring-only site (no code site exists for target_id): slugified,
            # so a hostile value can't smuggle a `"""` that terminates the
            # enclosing docstring early (DCR-0006). See `_slugify`'s docstring.
            target_id=target_id_display,
            slug=slug,
            decorators=decorators,
            compliance_inline=compliance_inline,
            owasp_llm=_fmt_ids(compliance.owasp_llm),
            owasp_asi=_fmt_ids(compliance.owasp_asi),
            mitre_atlas=_fmt_ids(compliance.mitre_atlas),
            nist=_fmt_ids(compliance.nist_ai_rmf),
            # Only the control template references these; harmless for the rest.
            # Docstring preview: slugified, so a hostile control value can't
            # smuggle a `"""` that terminates the enclosing docstring early.
            control_display=_slugify(control),
            # CODE-interpolation sites: rendered as Python literals, never as
            # bare strings, so an attacker-influenceable value can't terminate
            # the literal it sits in and start executing (DCR-0001, DCR-0002).
            exploit_filename=_py_literal(f"exploit_{exploit.pattern_id}.json"),
            control_literal=_py_literal(control),
            model_kwarg=model_kwarg,
            provider_kwarg=provider_kwarg,
        )

        return GeneratedTest(
            framework="pytest",
            filename=f"test_security_{slug}.py",
            source=source,
            exploit=exploit,
        )
